name: C/C++ CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
env:
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, '-rc') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && !contains(github.ref, '-rc') }}

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Add ARM architecture to APT
      run: sudo dpkg --add-architecture armhf

    - name: Setup APT repositories for ARM
      run: sudo mv sources.list /etc/apt/sources.list

    - name: Update APT repositories
      run: sudo apt-get update

    - name: Install ARM cross compiler
      run: sudo apt-get -y install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Install dependencies
      run: sudo apt-get install zlib1g-dev:armhf

    - name: Configure
      run: autoreconf && CC=arm-linux-gnueabihf-gcc ./configure --without-openssl --host=arm

    - name: Compile
      run: make sftp-server

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: sftp-server
        path: sftp-server

    - name: Release (pre-release)
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        artifacts: sftp-server
        
    - name: Update latest-rc tag
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-rc
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: sftp-server

    - name: Release (final)
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: sftp-server
        
    - name: Update latest tag
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        artifacts: sftp-server